# Generated by Django 3.2.19 on 2023-06-26 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_cost', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facilityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospects.business_prospect')),
            ],
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_paid', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('MPESA ', 'Mpesa'), ('CHEQUE', 'Cheque'), ('BANK-TRANSACTION', 'Bank Payment')], default='Mpesa', max_length=20)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facilityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospects.business_prospect')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='implementation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('golive_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_days', models.DurationField(blank=True)),
                ('license_due', models.DateField(default=django.utils.timezone.now)),
                ('implementation_report', models.FileField(blank=True, upload_to='documents/')),
                ('facility_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.receipt')),
            ],
        ),
    ]
